"""Shared builders for the two panels added on top of the original four.

The corpora under ``tests/dashboard_fixtures`` are read-only here - they belong to the
first four panels and are regenerated by their own script. What these two panels need
that those do not is a stored skill whose RECORDING IS STILL ON DISK, so the
correlation between a skill's steps and the screens it was learned on can be tested at
all; :func:`data_dir_with_recorded_skill` writes one through the real stores.

Nothing here touches a network, a model or a browser.
"""

from __future__ import annotations

import io
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any

import pytest

from skillweaver.contracts import (
    ActionResult,
    Box,
    Click,
    Element,
    ElementKind,
    ElementSource,
    Fingerprint,
    Observation,
    Point,
    Provenance,
    Screenshot,
    Skill,
    SkillStats,
    Trajectory,
    TrajectoryStep,
    TypeText,
    Verdict,
)

DOMAIN = "recorded.test"
RUN_ID = "rec0000001"
START = datetime(2026, 9, 18, 9, 0, tzinfo=UTC)

SKILL_CODE = """def run(ctx, company):
    field = ctx.see.find_text('Search', 'text_field')
    ctx.expect(bool(field), 'no search field on screen to click')
    ctx.ctl.click(field[0])
    ctx.ctl.type_text(company)
    rows = ctx.see.find_text(company, 'row')
    ctx.expect(bool(rows), 'the search returned no row')
    ctx.ctl.click(rows[0])
    return True
"""

VERIFIER_CODE = """def verify(ctx, result):
    return bool(ctx.see.find_text('Invoice detail'))
"""


def a_png(shade: int) -> bytes:
    """A tiny distinguishable PNG, so a matched screen is a real inline image."""
    from PIL import Image

    buffer = io.BytesIO()
    Image.new("RGB", (48, 30), (shade, shade, 255 - shade)).save(buffer, format="PNG")
    return buffer.getvalue()


class _Index:
    """The least that satisfies ``ElementIndex``; the store rebuilds it on load."""

    def __init__(self, elements: tuple[Element, ...]) -> None:
        self._elements = list(elements)

    def all(self) -> list[Element]:
        return list(self._elements)

    def by_kind(self, kind: ElementKind) -> list[Element]:
        return [e for e in self._elements if e.kind == kind]

    def find_text(self, *_: Any, **__: Any) -> list[Element]:
        return list(self._elements)

    def nearest(self, *_: Any, **__: Any) -> list[Element]:
        return list(self._elements)

    def containing(self, *_: Any, **__: Any) -> list[Element]:
        return list(self._elements)

    def best(self, *_: Any, **__: Any) -> list[Element]:
        return list(self._elements)


def _observe(shade: int, url: str, when: datetime) -> Observation:
    elements = (
        Element(
            box=Box(10, 10, 80, 18),
            kind=ElementKind.text_field,
            text="Search",
            stable_id="search",
            source=ElementSource.merged,
        ),
    )
    return Observation(
        screenshot=Screenshot(png=a_png(shade), width=48, height=30, scale=1.0, captured_at=when),
        elements=elements,
        index=_Index(elements),
        fingerprint=Fingerprint(f"fp{shade}", {"url": url}),
        url=url,
        taken_at=when,
    )


def data_dir_with_recorded_skill(root: Path, *, run_id: str = RUN_ID) -> Path:
    """A data directory holding one skill and the run it names, written by the real stores."""
    from skillweaver.skills.store import FileSkillStore
    from skillweaver.trajectory.store import TrajectoryFileStore

    steps: list[TrajectoryStep] = []
    actions = (Click(point=Point(40, 20)), TypeText(text="Acme"), Click(point=Point(40, 90)))
    for index, action in enumerate(actions):
        when = START + timedelta(seconds=index)
        steps.append(
            TrajectoryStep(
                index=index,
                action=action,
                before=_observe(20 + index * 30, f"{DOMAIN}/step{index}", when),
                after=_observe(30 + index * 30, f"{DOMAIN}/step{index + 1}", when),
                result=ActionResult(ok=True, elapsed_ms=120.0),
                verdict=Verdict(ok=True, reason="the screen advanced", source="model"),
            )
        )
    TrajectoryFileStore(root / "trajectories").save(
        Trajectory(
            run_id=run_id,
            task="Open the invoice for a company",
            domain=DOMAIN,
            steps=tuple(steps),
            ok=True,
            started_at=START,
            finished_at=START + timedelta(seconds=len(actions)),
        )
    )
    FileSkillStore(root / "skills").put(
        Skill(
            name="open_invoice",
            domain=DOMAIN,
            summary="Open a company's invoice from the list.",
            docstring="Searches the list and opens the matching row.",
            params={"company": {"type": "string", "description": "Company to look for"}},
            code=SKILL_CODE,
            requires=(),
            precondition=None,
            verifier_code=VERIFIER_CODE,
            provenance=Provenance(
                trajectory_id=run_id,
                task_text="Open the invoice for a company",
                model="test-model",
                created_at=START,
            ),
            version=1,
            stats=SkillStats(runs=3, successes=3, mean_ms=900.0),
        )
    )
    return root


@pytest.fixture(scope="module")
def recorded_dir(tmp_path_factory: pytest.TempPathFactory) -> Path:
    return data_dir_with_recorded_skill(tmp_path_factory.mktemp("recorded"))
